apiVersion: v1
kind: Pod
metadata:
  name: god
  labels:
    number: "03"
    mount: host-path
    containers: all

spec:
  restartPolicy: OnFailure
  containers:
    - image: scripts
      imagePullPolicy: IfNotPresent
      name: worker
      command: ["ash", "work.sh"]
      volumeMounts:
        - mountPath: /mnt
          name: db

    - image: scripts
      imagePullPolicy: IfNotPresent
      name: viewer
      command: ["ash", "view.sh"]
      volumeMounts:
        - mountPath: /mnt
          name: db
          readOnly: true

  volumes:
    - name: db
      hostPath:
        path: /tmp/k8s-practice/03/db
        type: DirectoryOrCreate
